# Generated by Django 2.0 on 2020-11-11 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NovelsData',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20, verbose_name='小说类别')),
                ('novel_name', models.CharField(max_length=20, verbose_name='小说书名')),
                ('title', models.CharField(max_length=50, verbose_name='小说标题')),
                ('desc', models.TextField(verbose_name='概述')),
                ('author', models.CharField(max_length=20, verbose_name='作者')),
                ('image', models.ImageField(upload_to='novels', verbose_name='小说图片')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('chapter_name', models.CharField(max_length=20, verbose_name='章节名称')),
            ],
            options={
                'verbose_name': '小说数据表',
                'verbose_name_plural': '小说数据表',
                'db_table': 'novels_data',
            },
        ),
    ]
